<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{

    public function run(): void
    {
        // **** Gurfaty
        DB::table('products')->insert([
            [
                'id' => 1,
                'name' => 'Leather Chair',
                'image' => 'http://127.0.0.1:8000/images/seeder/product/chair1.jpg',
                'price' => 30,
                'stock' => 'off',
                'descrption' => 'This is a comfortable leather chair with a sleek design.',
                'descrptionLong' => ' Elevate your comfort with our premium leather chair. 
            Its ergonomic design provides excellent lumbar support, 
            making it the perfect addition to your home or office. 
            The high-quality leather ensures durability and style.',
                'width' => '200',
                'height' => '700',
                'Depth' => '450',
                'Weight' => '500',
                'Qualitycheck' => 'yes',
                'quantity' => 30,
                'store_id' => 1,
                'category_id' => 2,
                'status' => 'active',
            ],
            [
                'id' => 3,
                'name' => 'Leather Chair',
                'image' => 'http://127.0.0.1:8000/images/seeder/product/chair2.jpg',
                'price' => 35,
                'stock' => 'off',
                'descrption' => 'This is a comfortable leather chair with a sleek design.',
                'descrptionLong' => ' Elevate your comfort with our premium leather chair. 
            Its ergonomic design provides excellent lumbar support, 
            making it the perfect addition to your home or office. 
            The high-quality leather ensures durability and style.',
                'width' => '200',
                'height' => '700',
                'Depth' => '450',
                'Weight' => '500',
                'Qualitycheck' => 'yes',
                'quantity' => 20,
                'store_id' => 1,
                'category_id' => 2,
                'status' => 'active',
            ],
            [
                'id' => 2,
                'name' => 'Sofa Chair',
                'image' => 'http://127.0.0.1:8000/images/seeder/product/sofa1.jpg',
                'price' => 50,
                'stock' => 'on',
                'descrption' => 'This is a comfortable Sofa chair with a sleek design.',
                'descrptionLong' => ' Elevate your comfort with our premium Sofa chair. 
            Its ergonomic design provides excellent lumbar support, 
            making it the perfect addition to your home or office. 
            The high-quality leather ensures durability and style.',
                'width' => '200',
                'height' => '700',
                'Depth' => '450',
                'Weight' => '500',
                'Qualitycheck' => 'yes',
                'quantity' => 10,
                'store_id' => 1,
                'category_id' => 1,
                'status' => 'active',
            ],
        ]);
        DB::table('products')->insert([
            'id' => 4,
            'name' => 'TV MOUNT',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/wall.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/wall2.jpg',
            'price' => 150,
            'stock' => 'on',
            'descrption' => 'This is a TV MOUNT with a sleek design.',
            'descrptionLong' => ' Elevate  with our premium TV MOUNT . 
        Its ergonomic design provides excellent lumbar support, 
        making it the perfect addition to your home or office. 
        The high-quality leather ensures durability and style.',
            'width' => '100',
            'height' => '680',
            'Depth' => '570',
            'Weight' => '900',
            'Qualitycheck' => 'yes',
            'quantity' => 12,
            'store_id' => 1,
            'category_id' => 4,
            'status' => 'active',
        ]);
        DB::table('products')->insert([
            'id' => 5,
            'name' => 'Dressing Table',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/DressingTable1.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/DressingTable2.jpg',
            'image3' => 'http://127.0.0.1:8000/images/seeder/product/DressingTable3.jpg',
            'image4' => 'http://127.0.0.1:8000/images/seeder/product/DressingTable4.jpg',
            'price' => 250,
            'stock' => 'off',
            'descrption' => 'Vandana Interiors Modern White Makeup Vanity Expandable Dressing Table with Cabinet Mirror & Stool Included',
            'descrptionLong' => 'Vandana Interiors Modern White Makeup Vanity Expandable Dressing Table with Cabinet Mirror & Stool Included',
            'width' => '100',
            'height' => '680',
            'Depth' => '570',
            'Weight' => '900',
            'Qualitycheck' => 'yes',
            'quantity' => 17,
            'store_id' => 1,
            'category_id' => 6,
            'status' => 'active',
        ]);
        DB::table('products')->insert([
            'id' => 6,
            'name' => 'Master Bed',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/bedroom.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/bedroom2.jpg',
            'price' => 250,
            'stock' => 'off',
            'descrption' => 'Vandana Interiors Modern White Makeup Vanity Expandable Dressing Table with Cabinet Mirror & Stool Included',
            'descrptionLong' => 'Vandana Interiors Modern White Makeup Vanity Expandable Dressing Table with Cabinet Mirror & Stool Included',
            'width' => '760',
            'height' => '340',
            'Depth' => '120',
            'Weight' => '780',
            'Qualitycheck' => 'yes',
            'quantity' => 30,
            'store_id' => 1,
            'category_id' =>6,
            'status' => 'active',
        ]);
// **** Meem
        DB::table('products')->insert([
            'id' => 7,
            'name' => 'Living Room',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/livingroom.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/livingroom2.jpg',
            'image3' => 'http://127.0.0.1:8000/images/seeder/product/livingroom3.jpg',
            'price' => 600,
            'stock' => 'off',
            'descrption' => 'It is essential for a living room to have a peaceful and friendly atmosphere, so selecting a color scheme that features warm neutrals such as stone tones, beiges, and creams is the best way to achieve this.',
            'descrptionLong' => 'Relax on your sofa inside and feel the breeze on your face thanks to the rooms open, airy design; youll feel like youre in the middle of nature. This living room is everything you are looking for!',
            'width' => '450',
            'height' => '970',
            'Depth' => '120',
            'Weight' => '340',
            'Qualitycheck' => 'yes',
            'quantity' => 12,
            'store_id' => 2,
            'category_id' =>8,
            'status' => 'active',
        ]);
        DB::table('products')->insert([
            'id' => 8,
            'name' => 'TV Stand',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/TVStand.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/TVStand2.jpg',
            'price' => 140,
            'stock' => 'off',
            'descrption' => 'This is new modern luxury adjustable TV stand with storage cabinets ',
            'descrptionLong' => 'made with oak wooden body and tempered glass top fit perfectly into any space because his adjustable length very unique and superior design to adds a contemporary shine to your living room super durable with sure warranty.',
            'width' => '765',
            'height' => '345',
            'Depth' => '213',
            'Weight' => '454',
            'Qualitycheck' => 'yes',
            'quantity' => 6,
            'store_id' => 2,
            'category_id' =>8,
            'status' => 'active',
        ]);
        DB::table('products')->insert([
            'id' => 9,
            'name' => 'Sofa Bed',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/sofabed.jpg',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/sofabed2.jpg',
            'image3' => 'http://127.0.0.1:8000/images/seeder/product/sofabed3.jpg',
            'price' => 100,
            'stock' => 'off',
            'descrption' => 'Natural Marble Oval Tea Table Scale Living Room Coffee Table Brushed Brass Coffee Table Black Glass Surface',
            'descrptionLong' => 'Relax on your sofa inside and feel the breeze on your face thanks to the rooms open, airy design; youll feel like youre in the middle of nature. This living room is everything you are looking for!',
            'width' => '465',
            'height' => '123',
            'Depth' => '453',
            'Weight' => '657',
            'Qualitycheck' => 'yes',
            'quantity' => 14,
            'store_id' => 2,
            'category_id' =>8,
            'status' => 'active',
        ]);
        DB::table('products')->insert([
            'id' => 10,
            'name' => 'Oval Table',
            'image2' => 'http://127.0.0.1:8000/images/seeder/product/table.jpg',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/table2.jpg',
            'price' => 100,
            'stock' => 'off',
            'descrption' => 'Natural Marble Oval Tea Table Scale Living Room Coffee Table Brushed Brass Coffee Table Black Glass Surface',
            'descrptionLong' => 'Relax on your sofa inside and feel the breeze on your face thanks to the rooms open, airy design; youll feel like youre in the middle of nature. This living room is everything you are looking for!',
            'width' => '465',
            'height' => '123',
            'Depth' => '453',
            'Weight' => '657',
            'Qualitycheck' => 'yes',
            'quantity' => 18,
            'store_id' => 2,
            'category_id' =>8,
            'status' => 'active',
        ]);

        DB::table('products')->insert([
            'id' => 11,
            'name' => 'Barstool Seat',
            'image' => 'http://127.0.0.1:8000/images/seeder/product/Chair.jpg',
            'price' => 45,
            'stock' => 'off',
            'descrption' => 'Eames Style Bar 31" Stool, Yellow w/Tall Wooden Base',
            'descrptionLong' => 'Beautiful Addition to your Home! Free Shipping on everything! Receive Coupons for life for future purchases on any product in our store!',
            'width' => '123',
            'height' => '123',
            'Depth' => '345',
            'Weight' => '768',
            'Qualitycheck' => 'yes',
            'quantity' => 13,
            'store_id' => 2,
            'category_id' =>2,
            'status' => 'active',
        ]);
    }
}
